FROM dockerfile/ubuntu

RUN \
  apt-get update && \
  apt-get -y upgrade && \
  apt-get install -y nodejs && \
  apt-get install -y npm && \
  rm -rf /var/lib/apt/lists/*

ADD server/package.json /opt/app/server/package.json

WORKDIR /opt/app/server

RUN npm install

ADD server/* /opt/app/server/

CMD ["nodejs", "server.js"]