FROM dockerfile/ubuntu

RUN \
  apt-get update && \
  apt-get -y upgrade && \
  apt-get install -y nodejs && \
  apt-get install -y npm && \
  rm -rf /var/lib/apt/lists/*

# the link is needed as nodemon uses hardcoded "node" binary
RUN ln -s /usr/bin/nodejs /usr/local/bin/node
RUN npm install -g nodemon

ADD server/package.json /opt/app/server/package.json

WORKDIR /opt/app/server

RUN npm install

ADD server/* /opt/app/server/

CMD ["nodejs", "server.js"]